path_to_texture = "/Users/andriylevitskyy/Desktop/reconstruction/aca95_texture_new0.png"
root = "/Users/andriylevitskyy/Desktop/reconstruction/python_code/"
path_to_position = root + "positions.pkl"
output_folder = "rendered_video"
model_folder = "fighter1_model"
